### ISSUE TITLE
Migrate users

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_legacy_migration#13]

**Comment by stephen-cox** [comment]
@andybroomfield @Adnan-cds This commit (https://github.com/localgovdrupal/localgov_legacy_migration/commit/53630f9ca5e128900e5a1b8275d58f8bc394064a) adds a user migration. It skips user 0 (anonymous) but migrates user 1.

I haven't done anything about user roles. We currently only specify an author and an editor role. I can add something to map roles between what you have on your current sites and what he have in LocalGov Drupal, but this is going to be unique for each site as you have different roles. I'll leave this for now, but do you have any thoughts about user role migration?

**Comment by andybroomfield** [comment]
Will open up another issue for roles, though this is one that we will likly want to create our own as we have very bespoke roles now for service specific content.

In general though for BHCC
communications => content designer
emergency publisher => emergency publisher
Everyone else is an authenticated user.

Directory editor is another role that may be getting used by localgov, so that would also need to map accross, though the permissions for those are a bit more involved.
